### PR TITLE
Added Moodo dataset

### PR DESCRIPTION
**Pull request by tintin10q**

### CODE REVIEW

**Comment by tintin10q** [comment]
Pull request for issue #2 @juansgomez87

**Comment by juansgomez87** [comment]
Thanks for your contribution!

**Comment by tintin10q** [comment]
You did not actually merge the contribution @juansgomez87 but you closed it. Is that what you wanted to do? Why did you not want to merge it?

**Comment by juansgomez87** [comment]
I added your contribution but sorted in time. This is why I closed it without merging. Thanks for helping out 🙏

**Comment by juansgomez87** [comment]
My bad, now you appear as a contributor :) thanks again!

**Pull request merged**
